library(tidyverse)
library(here)
data<-read.csv("Heatmap.csv", row.names = 1)
df<-t(scale(t(data)))
png("~/Desktop/ss.png", width = 40, height = 35)
library(gplots)
library(RColorBrewer)
heatmap.2(df,col=brewer.pal(11,"RdBu"),keysize=1.0,key=T,dendrogram="col",margins =c(25,10),lhei = c(1,7),lwid = c(1,7),scale = "row",notecol="black",density.info="none",trace="none",cexRow=1.3,cexCol=3)
dev.off()
