library(pheatmap)
data <- read.csv("seq2.csv", check.names = F, row.names = "Gene")
df <- t(scale(t(data)))
pdf("~/Desktop/p3.pdf", width = 16, height = 12)
pheatmap(df)
dev.off()
pdf("~/Desktop/p4.pdf", width = 16, height = 12)
pheatmap(df, cutree_rows = 2, cluster_col = FALSE, fontsize = 10)
dev.off()